cursoProgramacion/Models/Calculadora.cs
using System.ComponentModel.DataAnnotations;

namespace cursoProgramacion.Models;

public class Calculadora
{
    public int Operador1 { get; set; }
    public int Operador2 { get; set; }
    public string? Accion { get; set; }
    [Display(Name = "La respuesta es: ")]
    public int Respuesta { get; set; }
}

cursoProgramacion/Models/Contacto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace cursoProgramacion.Models
{
    public class Contacto
    {
        [Required(ErrorMessage="Campo Nombre incompleto")]
        [Display(Name="Nombre")]
        public string? Name { get; set; }
        [Required(ErrorMessage="Campo Apellido incompleto")]
        [Display(Name="Apellido")]
        public string? Lastname { get; set; }

        [Display(Name="Correo")]
        public string? Email { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name="Telefono")]
        public int Number { get; set; }
        [Display(Name="Curso")]
        public string? Course { get; set; }
        [Display(Name="Titulo")]
        public string? Title { get; set; }
        [Display(Name="Mensage")]
        public string? Message { get; set; }
        public string? Response { get; set; }
        
    }
}

cursoProgramacion/Models/ErrorViewModel.cs
namespace cursoProgramacion.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

cursoProgramacion/Controllers/CalculadoraController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using cursoProgramacion.Models;

namespace cursoProgramacion.Controllers;

public class CalculadoraController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public CalculadoraController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public IActionResult calcular(Calculadora obCalculadora){
        if("+".Equals(obCalculadora.Accion)){
            obCalculadora.Respuesta = obCalculadora.Operador1 + obCalculadora.Operador2;
        }
         if("-".Equals(obCalculadora.Accion)){
            obCalculadora.Respuesta = obCalculadora.Operador1 - obCalculadora.Operador2;
        }
         if("*".Equals(obCalculadora.Accion)){
            obCalculadora.Respuesta = obCalculadora.Operador1 * obCalculadora.Operador2;
        }
         if("/".Equals(obCalculadora.Accion)){
            obCalculadora.Respuesta = obCalculadora.Operador1 / obCalculadora.Operador2;
        }
        return View("Index", obCalculadora);
    }
}

cursoProgramacion/Controllers/ContactoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using cursoProgramacion.Models;

namespace cursoProgramacion.Controllers;

public class ContactoController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public ContactoController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    public IActionResult Registrar(Contacto objcontacto){
        if (ModelState.IsValid)
        {
            objcontacto.Response="Gracias, lo contactaremos";   
        }
        return View("Index", objcontacto);
    }
}

cursoProgramacion/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using cursoProgramacion.Models;

namespace cursoProgramacion.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

cursoProgramacion/Views/Calculadora/Index.cshtml
@model cursoProgramacion.Models.Calculadora;//a;adiendo controles 
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Calculadora</h1>
    <form asp-controller="Calculadora" asp-action="calcular">
        <label>Calculadora</label>
        <br>
        <label>Operador 1</label>
        <input asp-for="Operador1">
        <br>
        <label>Operador 2</label>
        <input asp-for="Operador2">
        <br>
        <label>Elija la accion</label>
        <select asp-for="Accion">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value="/">/</option>
        </select>
        <br>
        <input type="submit" value="calcular">
    </form>
    <td>@Html.DisplayNameFor(model => model.Respuesta)</td>
    <td>@Html.DisplayTextFor(model => model.Respuesta)</td>
</div>

cursoProgramacion/Views/Contacto/Index.cshtml
@model cursoProgramacion.Models.Contacto;
@{
    ViewData["Title"] = "Home Page";
}

<div class="container col-md-4">
    <h1>Formulario contacto</h1>
    <form asp-controller="Contacto" asp-action="Registrar">
        <div>
            <label asp-for="Name" class="control-label"></label>
            <input type="text" asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Lastname" class="control-label"></label>
            <input type="text" asp-for="Lastname" class="form-control">
            <span asp-validation-for="Lastname" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Email" class="control-label"></label>
            <input type="text" asp-for="Email" class="form-control">
        </div>
        <div>
            <label asp-for="Number" class="control-label"></label>
            <input type="text" asp-for="Number" class="form-control">
            <span asp-validation-for="Number" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Course" class="control-label"></label>
            <select asp-for="Course" class="form-control">
                <option value="Matematica">Matematica</option>
                <option value="Comunicacion">Comunicacion</option>
            </select>
        </div>
        <div>
            <label asp-for="Title" class="control-label"></label>
            <input type="text" asp-for="Title" class="form-control">
        </div>
        <div>
            <label asp-for="Message" class="control-label"></label>
            <textarea asp-for="Message" class="form-control"></textarea>
        </div>
        <div style="text-align: center;">
            <button type="submit" class="btn btn-primary">Registrar</button>
        </div>
    </form>
    <td>@Html.DisplayTextFor(model => model.Response)</td>
</div>

cursoProgramacion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

cursoProgramacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cursoProgramacion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cursoProgramacion.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cursoProgramacion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - cursoProgramacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>